/* eslint-disable @next/next/no-sync-scripts */
import Header from "@/components/Header/Header";
import BookingList from "@/components/Section/BookingList";
import InputSection from "@/components/Section/InputData";

import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="../img/favicon.png" />
        <title>Flight Booking App | Redux Fundamental Example</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <section>
        <Header />
        <InputSection />
        <BookingList />
        <Link href="/flight" className="text-white">
          flight
        </Link>
      </section>
    </>
  );
}
